### ISSUE TITLE
Please add board schematic

### ISSUE THREAD

**Issue by ddekanski** [WeActStudio/WeActStudio.ESP32S3-MINI#1]
Your board has been available on Aliexpress for months, but its schematic is nowhere to be found. Would you be so kind and add it in this repository?

**Comment by matsekberg** [comment]
I would also need a schematic in order to be prepared to build my products on the board. Your boards have great quality and are very attractive to incorporate in products but I need full documentation in order to be able to do my design with them.

**Comment by fritolays** [comment]
Has it not been here since the original commit?
https://github.com/WeActStudio/WeActStudio.ESP32S3-MINI/blob/main/Hardware/ESP32_S3_MINI_Sch.pdf
